name: Checks
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow this workflow to be called by other workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  openapi-lint-checks:
    runs-on: ubuntu-latest
    name: OpenAPI Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx @redocly/cli lint api/v3/openapi.yaml
  openapi-validation:
    runs-on: ubuntu-latest
    name: Validate OpenAPI Spec
    steps:
      - uses: actions/checkout@v3
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: api/v3/openapi.yaml